// components/CreativeShowcase.vue
<template>
  <section class="creative-showcase">
    <div class="container-bb">
      <!-- 标题 -->
      <h1 class="showcase-title">{{ t('creative.title') || '更多创意元素！' }}</h1>

      <!-- 图片轮播 -->
      <div class="carousel-container">
        <button
          class="carousel-arrow carousel-arrow-left"
          @click="previousSlide"
          :disabled="currentSlide === 0"
        >
          <div class="i-fa6-solid-chevron-left" />
        </button>

        <div class="carousel-wrapper">
          <div
            class="carousel-track"
            :style="{ transform: `translateX(-${currentSlide * 100}%)` }"
          >
            <div
              v-for="(image, index) in images"
              :key="index"
              class="carousel-slide"
            >
              <img
                :src="`http://154.21.200.80:8889/png/魔改${index + 1}.jpg`"
                :alt="`魔改${index + 1}`"
                class="carousel-image"
                @error="handleImageError"
              />
            </div>
          </div>
        </div>

        <button
          class="carousel-arrow carousel-arrow-right"
          @click="nextSlide"
          :disabled="currentSlide >= images.length - 1"
        >
          <div class="i-fa6-solid-chevron-right" />
        </button>
      </div>

      <!-- 描述 -->
      <p class="showcase-description">
        {{ t('creative.description') || '你永远可以无限制地想象蚕豆能给你带来什么惊喜。' }}
      </p>

      <!-- 探索按钮 -->
      <a href="https://drive.30hb.cn/" class="explore-button">
        <img
          src="http://154.21.200.80:8889/png/绿色按钮.png"
          alt=""
          class="button-bg"
        />
        <span class="button-text">{{ t('creative.explore') || '探索更多>>' }}</span>
      </a>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

const currentSlide = ref(0)
const images = Array.from({ length: 4 }, (_, i) => i)
let intervalId: NodeJS.Timeout | null = null

const previousSlide = () => {
  if (currentSlide.value > 0) {
    currentSlide.value--
  }
}

const nextSlide = () => {
  if (currentSlide.value < images.length - 1) {
    currentSlide.value++
  }
}

const handleImageError = (event: Event) => {
  const img = event.target as HTMLImageElement
  img.style.display = 'none'
}

// 自动轮播 - 仅在客户端
onMounted(() => {
  intervalId = setInterval(() => {
    if (currentSlide.value < images.length - 1) {
      currentSlide.value++
    } else {
      currentSlide.value = 0
    }
  }, 5000)
})

onUnmounted(() => {
  if (intervalId) {
    clearInterval(intervalId)
  }
})
</script>

<style scoped>
.creative-showcase {
  padding: 4rem 1rem;
  background: linear-gradient(to bottom, rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 0.8));
}

.showcase-title {
  font-size: 3rem;
  font-weight: 900;
  color: #2C2416;
  text-align: center;
  margin: 0 0 3rem;
}

.carousel-container {
  position: relative;
  display: flex;
  align-items: center;
  gap: 2rem;
  max-width: 1000px;
  margin: 0 auto 2rem;
}

.carousel-arrow {
  flex-shrink: 0;
  width: 50px;
  height: 50px;
  border-radius: 50%;
  background: rgba(8, 145, 209, 0.9);
  border: none;
  color: white;
  font-size: 1.5rem;
  cursor: pointer;
  transition: all 0.3s;
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 10;
}

.carousel-arrow:hover:not(:disabled) {
  background: rgba(8, 145, 209, 1);
  transform: scale(1.1);
}

.carousel-arrow:disabled {
  opacity: 0.3;
  cursor: not-allowed;
}

.carousel-wrapper {
  flex: 1;
  overflow: hidden;
  border-radius: 16px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.15);
}

.carousel-track {
  display: flex;
  transition: transform 0.5s ease-in-out;
}

.carousel-slide {
  min-width: 100%;
  aspect-ratio: 16 / 9;
}

.carousel-image {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.showcase-description {
  font-size: 1.25rem;
  color: #5C5446;
  text-align: center;
  margin: 2rem 0;
  font-weight: 500;
}

.explore-button {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  min-width: 250px;
  min-height: 60px;
  margin: 0 auto;
  text-decoration: none;
  transition: transform 0.2s, filter 0.2s;
  cursor: pointer;
}

.explore-button:hover {
  transform: scale(1.05);
  filter: brightness(1.1);
}

.explore-button:active {
  transform: scale(0.98);
}

.button-bg {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: fill;
}

.button-text {
  position: relative;
  z-index: 1;
  font-size: 1.25rem;
  font-weight: 700;
  color: white;
  text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.8);
}

@media (max-width: 768px) {
  .creative-showcase {
    padding: 2rem 0.5rem;
  }

  .showcase-title {
    font-size: 2rem;
  }

  .carousel-container {
    gap: 1rem;
  }

  .carousel-arrow {
    width: 40px;
    height: 40px;
    font-size: 1.25rem;
  }

  .carousel-arrow-left,
  .carousel-arrow-right {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
  }

  .carousel-arrow-left {
    left: 0.5rem;
  }

  .carousel-arrow-right {
    right: 0.5rem;
  }

  .showcase-description {
    font-size: 1rem;
    padding: 0 1rem;
  }

  .explore-button {
    min-width: 200px;
    min-height: 50px;
  }

  .button-text {
    font-size: 1rem;
  }
}
</style>

// next-app/src/components/creative-showcase.tsx
"use client"

import { useState, useEffect } from "react"
import { ChevronLeft, ChevronRight } from "lucide-react"
import { useLocale } from "@/contexts/locale-context"
import { getDictionary } from "@/lib/i18n"

const ASSETS = "http://154.21.200.80:8889/png"
const SLIDES = 4

export function CreativeShowcase() {
  const locale = useLocale()
  const dict = getDictionary(locale)
  const [currentSlide, setCurrentSlide] = useState(0)

  useEffect(() => {
    const id = setInterval(() => {
      setCurrentSlide((s) => (s < SLIDES - 1 ? s + 1 : 0))
    }, 5000)
    return () => clearInterval(id)
  }, [])

  const handleImageError = (e: React.SyntheticEvent<HTMLImageElement>) => {
    e.currentTarget.style.display = "none"
  }

  return (
    <section className="bg-gradient-to-b from-white/50 to-white/80 px-4 py-16">
      <div className="mx-auto max-w-7xl">
        <h2 className="mb-12 text-center text-3xl font-black text-[#2C2416] md:text-5xl">
          {dict.creative.title}
        </h2>

        <div className="relative mx-auto mb-8 flex max-w-[1000px] items-center gap-8">
          <button
            type="button"
            disabled={currentSlide === 0}
            onClick={() => setCurrentSlide((s) => Math.max(0, s - 1))}
            className="absolute left-2 z-10 flex h-10 w-10 shrink-0 cursor-pointer items-center justify-center rounded-full border-none bg-[rgba(8,145,209,0.9)] text-white transition-all hover:scale-110 disabled:cursor-not-allowed disabled:opacity-30 md:static md:left-0 md:h-12 md:w-12"
            aria-label="Previous"
          >
            <ChevronLeft className="h-6 w-6" />
          </button>

          <div className="min-w-0 flex-1 overflow-hidden rounded-2xl shadow-[0_8px_32px_rgba(0,0,0,0.15)]">
            <div
              className="flex transition-transform duration-500 ease-in-out"
              style={{ transform: `translateX(-${currentSlide * 100}%)` }}
            >
              {Array.from({ length: SLIDES }, (_, i) => (
                <div key={i} className="aspect-video min-w-full">
                  <img
                    src={`${ASSETS}/%E9%AD%94%E6%94%B9${i + 1}.jpg`}
                    alt={`魔改${i + 1}`}
                    className="h-full w-full object-cover"
                    onError={handleImageError}
                  />
                </div>
              ))}
            </div>
          </div>

          <button
            type="button"
            disabled={currentSlide >= SLIDES - 1}
            onClick={() => setCurrentSlide((s) => Math.min(SLIDES - 1, s + 1))}
            className="absolute right-2 z-10 flex h-10 w-10 shrink-0 cursor-pointer items-center justify-center rounded-full border-none bg-[rgba(8,145,209,0.9)] text-white transition-all hover:scale-110 disabled:cursor-not-allowed disabled:opacity-30 md:static md:right-0 md:h-12 md:w-12"
            aria-label="Next"
          >
            <ChevronRight className="h-6 w-6" />
          </button>
        </div>

        <p className="mx-auto mb-8 mt-8 text-center text-lg font-medium text-[#5C5446] md:text-xl">
          {dict.creative.description}
        </p>

        <a
          href="https://drive.30hb.cn/"
          target="_blank"
          rel="noopener noreferrer"
          className="relative mx-auto flex min-h-[60px] min-w-[200px] cursor-pointer items-center justify-center no-underline transition-[transform,filter] hover:scale-105 hover:brightness-110 active:scale-[0.98] md:min-w-[250px]"
        >
          <img
            src={`${ASSETS}/%E7%BB%BF%E8%89%B2%E6%8C%89%E9%92%AE.png`}
            alt=""
            className="absolute inset-0 h-full w-full object-fill"
            aria-hidden
          />
          <span className="relative z-10 text-lg font-bold text-white drop-shadow-[2px_2px_4px_rgba(0,0,0,0.8)] md:text-xl">
            {dict.creative.explore}
          </span>
        </a>
      </div>
    </section>
  )
}
