// next-app/src/components/comments-section.tsx
"use client"

import { useEffect, useRef } from "react"
import { useLocale } from "@/contexts/locale-context"
import { getDictionary } from "@/lib/i18n"

export function CommentsSection() {
  const locale = useLocale()
  const dict = getDictionary(locale)
  const containerRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!containerRef.current) return
    let mounted = true
    import("@waline/client").then(({ init }) => {
      if (!mounted || !containerRef.current) return
      import("@waline/client/waline.css")
      init({
        el: containerRef.current,
        serverURL: "https://waline.saop.cc",
        path: "disk.saop.cc",
      })
    }).catch(console.error)
    return () => {
      mounted = false
    }
  }, [])

  return (
    <section className="bg-white/30 px-4 py-16">
      <div className="mx-auto max-w-7xl">
        <h2 className="mb-12 text-center text-2xl font-black text-[#2C2416] md:text-4xl">
          {dict.comments.title}
        </h2>
        <div className="mx-auto max-w-[900px] rounded-2xl bg-white p-8 shadow-[0_4px_16px_rgba(0,0,0,0.1)]">
          <div ref={containerRef} />
        </div>
      </div>
    </section>
  )
}

// components/CommentsSection.vue
<template>
  <section class="comments-game">
    <div class="container-bb">
      <!-- 标题 -->
      <div class="comments-header">
        <h2 class="comments-title">
          {{ t('comments.title') || '玩家评论' }}
        </h2>
      </div>

      <!-- 评论容器 -->
      <div class="comments-container">
        <div id="waline" />
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

onMounted(async () => {
  try {
    const { init } = await import('@waline/client')
    await import('@waline/client/waline.css')

    init({
      el: '#waline',
      serverURL: 'https://waline.saop.cc',
      path: 'disk.saop.cc'
    })
  } catch (err) {
    console.error('Failed to load Waline:', err)
  }
})
</script>

<style scoped>
.comments-game {
  padding: 4rem 1rem;
  background: rgba(255, 255, 255, 0.3);
}

.comments-header {
  text-align: center;
  margin-bottom: 3rem;
}

.comments-title {
  font-size: 2.5rem;
  font-weight: 900;
  color: #2C2416;
  margin: 0;
}

.comments-container {
  max-width: 900px;
  margin: 0 auto;
  background: white;
  border-radius: 16px;
  padding: 2rem;
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.1);
}

@media (max-width: 640px) {
  .comments-game {
    padding: 2rem 0.5rem;
  }

  .comments-title {
    font-size: 2rem;
  }

  .comments-container {
    padding: 1rem;
  }
}
</style>
